# This workflow will build and test an Xcode project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Xcode

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: List available simulators
      run: xcrun simctl list devices
    - name: Build
      run: xcodebuild -project TeaDiagnoseApp.xcodeproj -scheme TeaDiagnoseApp -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.2' build
    - name: Run tests
      run: xcodebuild test -project TeaDiagnoseApp.xcodeproj -scheme TeaDiagnoseApp -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.2'