name: Xcode Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Project configuration - adjust these if needed
  PROJECT_NAME: TeaDiagnoseApp.xcodeproj
  SCHEME_NAME: TeaDiagnoseApp  # Note: Originally requested as "tea-diagnose" but actual scheme is "TeaDiagnoseApp"

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: List available simulators
      run: xcrun simctl list devices available
    
    - name: Build project
      run: |
        xcodebuild -project ${{ env.PROJECT_NAME }} \
                   -scheme ${{ env.SCHEME_NAME }} \
                   -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
                   clean build \
                   CODE_SIGNING_ALLOWED=NO
    
    - name: Run tests
      run: |
        xcodebuild -project ${{ env.PROJECT_NAME }} \
                   -scheme ${{ env.SCHEME_NAME }} \
                   -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
                   test \
                   CODE_SIGNING_ALLOWED=NO