# This workflow will build and test an Xcode project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Xcode

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    
    - name: Build
      run: xcodebuild -project TeaDiagnoseApp.xcodeproj -scheme TeaDiagnoseApp -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' build
    
    - name: Run tests
      run: xcodebuild test -project TeaDiagnoseApp.xcodeproj -scheme TeaDiagnoseApp -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'